# Generated by Django 2.2.6 on 2019-10-14 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0013_auto_20190905_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemodel',
            name='anime_image',
            field=cloudinary.models.CloudinaryField(default='output/anime/anime.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='facemosaicmodel',
            name='facemosaic_image',
            field=cloudinary.models.CloudinaryField(default='output/facemosaic/facemosaic.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='facemosaicmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='facereadmodel',
            name='faceread_image',
            field=cloudinary.models.CloudinaryField(default='output/faceread/faceread.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='facereadmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='graymodel',
            name='gray_image',
            field=cloudinary.models.CloudinaryField(default='output/gray/gray.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='graymodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mosaicmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mosaicmodel',
            name='mosaic_image',
            field=cloudinary.models.CloudinaryField(default='output/mosaic/mosaic.jpg', max_length=255),
        ),
    ]
