# Generated by Django 2.2.6 on 2019-10-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0015_auto_20191014_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graymodel',
            name='gray_image',
            field=models.ImageField(upload_to='output/gray'),
        ),
    ]
