# Generated by Django 2.2.6 on 2019-10-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0017_auto_20191016_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graymodel',
            name='image',
            field=models.ImageField(upload_to='input/gray'),
        ),
    ]
