# Generated by Django 2.2.6 on 2019-10-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0021_auto_20191016_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graymodel',
            name='gray_image',
            field=models.ImageField(upload_to='output/gray'),
        ),
    ]
